steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/ml-ops-dog-breeds/dog_breeds_image', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/ml-ops-dog-breeds/dog_breeds_image']
