name: "Run codecheck"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.5

    - name: Ruff check and format
      run: |
        pip install ruff
        # pip install mypy
        ruff check .
        ruff format .
        # mypy .
